#
# This file contains configuration flags to customize your site
#
# Name of your site (displayed in the header)
name: John's Meat Locker
# Short bio or description (displayed in the header)
description: Explicit restaurant reviews.
#
# !! You don't need to change any of the configuration flags below !!
#
markdown: redcarpet
highlighter: pygments
permalink: /:title/
# The release of Jekyll Now that you're using
version: v1.0.0
# Set the Sass partials directory, as we're using @imports
sass:
sass_dir: _scss
style: :expanded # You might prefer to minify using :compressed
# Use the following plug-ins
gems:
- jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
# Exclude these files from your production _site
exclude:
- Gemfile
- Gemfile.lock
- LICENSE
- README.md
